M48
; DRILL file KiCad 10.0.1 date 2026-04-21T15:10:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-21T15:10:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X56.8Y-82.85
X98.0Y-82.9
T2
X77.61Y-45.11
M30
