M48
; DRILL file KiCad 10.0.1 date 2026-04-21T15:10:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-21T15:10:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X69.342Y-49.276
X69.342Y-51.816
X85.725Y-49.276
X85.725Y-51.816
T2
X77.5Y-56.0
X77.5Y-76.0
M30
